// Bundled, pre-generated audio for built-in phrases. These play with no AI, no
// API key, and no dependency on the device having a Telugu voice installed — the
// files ship with the app. Generated by scripts/gen-audio.mjs.
//
// Files are named by a hash of the Telugu-script text, so any code that already
// calls tts.speak(te) resolves to the right clip with zero extra plumbing.
// The SAME hash function lives in the generator script — keep them identical.

export function hashText(s: string): string {
  let h = 0x811c9dc5; // FNV-1a, 32-bit
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

const available = new Set<string>();
let loaded = false;

export async function initLocalAudio(): Promise<void> {
  try {
    const res = await fetch("/audio/manifest.json");
    if (res.ok) {
      const list = (await res.json()) as string[];
      for (const h of list) available.add(h);
    }
  } catch {
    /* no bundled audio present — features fall back to the browser voice */
  } finally {
    loaded = true;
  }
}

export function hasLocalAudio(text: string): boolean {
  return loaded && available.has(hashText(text));
}

export function hasLocalAudioLibrary(): boolean {
  return available.size > 0;
}

export function localAudioUrl(text: string): string {
  return `/audio/${hashText(text)}.mp3`;
}
